### ISSUE TITLE
Enable teh configuration of legend's label formatter in advanced mode

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts-editor#100]
It would be great to make it possible to configure label formatter such as this one in advanced mode : 

http://jsfiddle.net/hAnCr/790/

**Comment by TorsteinHonsi** [comment]
You can - this is what the `labelFormat` option is for: http://jsfiddle.net/highcharts/hAnCr/792/.

All formatters have `format` counterparts. The only thing you can't do with the format is advanced calculation and logic.

**Comment by berdeter** [comment]
Great. Thank you
