### ISSUE TITLE
Charts broken in IE

### ISSUE THREAD

**Issue by phoenixrip** [highcharts/highcharts-editor#105]
I must be doing something wrong here as I can't find anyone who has this issue elsewhere, but I cannot get the editor to give me a chart that works in IE.

The exported HTML option displays nicely in chrome and safari, but in IE the tooltips, selectable legend, and the flexible width are all gone, leaving essentially just an image of the chart in IE.

Is this a known issue or am I being an idiot?

alternatively... is there a way to use the export json to pass the created options to an inline script like the highchart demos are that IE will like?

I have this working nicely in chrome and safari, but it won't display anything in IE

```
<script >
	
	$(document).ready(function() {


	$.getJSON( 'https://www.samedomain.co.uk/chartoptions.json', function( options ) {
    new Highcharts.Chart(options);
		});

	});

</script>

```
 

Thanks in advance and apologies if this is confusing

**Comment by cvasseng** [comment]
Hi,

thanks for reporting, and sorry about the delay. I've added a fix for this in master. A new prebuilt will arrive later today or tomorrow.
