### ISSUE TITLE
Editor not working on Internet Explorer 11

### ISSUE THREAD

**Issue by ElGringo** [highcharts/highcharts-editor#107]
Hello,

I am trying to get the standalone version to work in the Internet Explorer 11. I am always getting an "Object.keys: The argument is not an object" error (highcharts-editor.min.js, Line: 30, Row: 22672).
I get the same error message on the test page http://editor.highcharts.com/full.html
 To narrow it down I inlcluded an unminified version of high-charts-editor.js (I took the one from the "app" directory of the windows version") which strangely did not produce this error but placed the right menu on top of the screen (screenshot).  

Any suggestions? Oh, btw. I tried the Version 0.1.1 

Thank you 

Rico
![hc](https://cloud.githubusercontent.com/assets/615067/21503809/4c4dfda4-cc5a-11e6-884b-1a85997fa69d.PNG)

**Comment by cvasseng** [comment]
Hi,

if you downloaded a prebuilt version from the releases, could you try cloning the repository and building it yourself? I fixed a similar issue to this a while ago, but haven't updated the prebuilts with the changes yet.


Doing 
    
    git clone https://github.com/highcharts/highcharts-editor
    cd highcharts-editor
    npm install
    gulp

should produce a build in the `dist/` folder.

**Comment by ElGringo** [comment]
Great! Many thanks! Worked like a charm.

**Comment by cvasseng** [comment]
Great to hear!

A new prebuilt with the latest fixes will come shortly. I'm leaving this open until then as a reference to others that may have the same issue in the meantime.

**Comment by cvasseng** [comment]
New release has now been published, so closing this.
