### ISSUE TITLE
highcharts editor with vue components

### ISSUE THREAD

**Issue by cpfarher** [highcharts/highcharts-editor#108]
I try to use standalone version of highcharts-editor in a component for vue js but I have a problem...
The console of the browser show an error: 

> Cannot read property 'cr' of undefined at highcharts-editor.js line 654.
`n = highed.dom.cr('link');`

obviously is because highed.dom is undefined.... It is a consequence that I use vue component and with it "shadow dom"? Or there is any other reason?

**Comment by cvasseng** [comment]
Hi,

sorry about the delay.

The error you're getting seems to be unrelated to shadow DOM things, but I'm not very familiar with the way vue handles things.

How are you including the editor? Are you using the prebuilt sources, or have you built your own? And if the latter - have you made any modifications to the the editor?

It would be very helpful to get a minimal sample demonstrating the error, if possible.

**Comment by cpfarher** [comment]
Hi, I trying to use highcharts editor in a vue component (https://github.com/bys-control/highcharts-editor). 
I try with pre build sources and buil it by my own.... I don't do modifications to the editor-
If you see the code in test directory you have a test file where all works fine. The problem is when I used the same vue component in another vue component of my app... I will modify the project and create a github repository in order to bring to you a similar app with the error.
Thank you.

**Comment by strategeens** [comment]
same issue.
trying to add this as a component(bower.json file) to my app, but i am getting this error "highed.dom is undefined"

**Comment by cvasseng** [comment]
90d3a61 contains a potential fix to this.

If it still doesn't work, I'd appreciate it if either of you could send me a bundle with a complete, working (or not working, as it is) demonstration of the issue.

**Comment by Saonela** [comment]
Seems like it fixed the problem. Thanks for quick response !

**Comment by cvasseng** [comment]
Thanks @Saonela.

Based on the feedback here and other places, it looks like this patch took care of it. It will be included in the next prebuilt release.
