### ISSUE TITLE
Edit existing chart

### ISSUE THREAD

**Issue by ld0rman** [highcharts/highcharts-editor#110]
Is there any way to edit a chart that has already been created? Say we make a chart with the editor and then we realise that we have made a mistake that we need to adjust ?

**Comment by cvasseng** [comment]
Hi,

you can load/save a chart by clicking the gear icon and choosing the "Load Project"/"Save Project" options. Note that this functionality does not work as expected in the current prebuilt sources, so you should build manually by cloning the repository and running `gulp` (built ends up in `dist/`). A new prebuilt version is incoming shortly.

**Comment by ld0rman** [comment]
Sorry I didn't find this myself. Works great!

**Comment by cvasseng** [comment]
No problem! Glad it worked out for you.
