### ISSUE TITLE
Font sizes in font editor not showing.

### ISSUE THREAD

**Issue by phoenixrip** [highcharts/highcharts-editor#113]
The drop down menus for font sizes work, but the menu is empty, no sizes are written in.

This is true of every version I've tried, including the demo here: http://editor.highcharts.com/full.html

Is there a way of fixing this?

**Comment by cvasseng** [comment]
The fix will be part of the next prebuilt.

In the meantime you can build your own editor by cloning the repository and running `npm install && gulp`, which produces bundles in `dist/`.

**Comment by phoenixrip** [comment]
Wonderful :) Thank you!
