### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by schester44** [highcharts/highcharts-editor#116]
It appears some of the documentation may be out of date, specifically the Plugins page. While attempting to register a plugin, i was unable to get `highed.plugins.use` to work but `highed.plugins.editor.use` worked as expected (jquery-simple-rest plugin)

Also, the sections "Example: Register a basic CSV plugin" and "Example: Register a Socrata plugin" use two completely different install methods. one uses `highed.plugins.import.install` the other `highed.importPlugins.install`, not sure if that was an oversight or if thats how the install methods are actually coded.

My apologies if these are non issues. I really appreciate the great work of this editor thus far and look forward to future iterations!

**Comment by schester44** [comment]
Ok, so branching off of this.. Maybe i'm doing something wrong.

When creating a plugin using `highed.plugins.export.install`, then registering it via something like `highed.Editor('editor-container', { plugins: ['jquery-simple-rest'] })`, i get the error `highed.plugins.use is not a function` on line 12277 of the unmidified highcharts-editor.js in dist/


Is it possible that I could have possibly disabled the use of plugins somewhere while building the editor?

**Comment by cvasseng** [comment]
Thanks for letting us know.

`highed.plugins.editor.use` and `highed.plugins.import.install` are the correct ones.

I've updated plugin docs now.

Thanks!
