### ISSUE TITLE
Thousands sep change not working after export.

### ISSUE THREAD

**Issue by phoenixrip** [highcharts/highcharts-editor#120]
Although the `thousandsSep` change (eg ` (',') ` ) now works as expected on load, and in the chart preview;

The change that is made to the thousandsSep is not reflected on exporting to HTML, or JSON or beautifiedJS.
The thousandsSep reverts to it's default` ' ' `in all the interactive versions of the chart.

Interestingly, the ',' is correctly displayed on exported SVG, and in the editor preview panel :)

It seems to be that` lang: ` options will only apply if they're in `Highcharts.setOptions` and the editor can only put them in  `Highcharts.Chart`.

**Comment by cvasseng** [comment]
Thanks for reporting!

Fixed in master now. :)
