### ISSUE TITLE
Chart exported as html has script with external files

### ISSUE THREAD

**Issue by Saonela** [highcharts/highcharts-editor#121]
As the title says, when you create chart with editor and export it as html (chart.export.html) , it becomes exported with additional script, which contains couple hardcoded libraries. This causes some unexpected behaviour and conflicts between existing files. 
![screenshot from 2017-01-25 13 26 39](https://cloud.githubusercontent.com/assets/13929110/22289014/22463aee-e302-11e6-8969-341871a4fbd7.png)

**Comment by Saonela** [comment]
As the title says, when you create chart with editor and export it as html (chart.export.html) , it becomes exported with additional script, which contains couple hardcoded libraries. This causes some unexpected behaviour and conflicts between existing files. 
![Uploading Screenshot from 2017-01-25 13:26:39.png…]()

**Comment by cvasseng** [comment]
As of commit 	9203c5c you can set `highed.option('includeCDNInExport', false);` to not include CDN scripts in the export.

This needs to be done somewhere on the page in which you include the editor.

**Comment by cvasseng** [comment]
@sbt2486: there's a bug in 2.x with setting it with two arguments, but the first argument to `highed.option` can also be an object, so you could try doing `highed.option({'includeCDNInExport': false});` before you initialize your editor instance. 

E.g.
```
    highed.ready(function () {
        highed.option({'includeCDInExport': false});
        highed.DrawerEditor(document.body);
    });
```

**Comment by sbt2486** [comment]
@cvasseng cheers man, it works when passing in an object.
