### ISSUE TITLE
How can i get the pie percentage?

### ISSUE THREAD

**Issue by popoycol** [highcharts/highcharts-editor#128]
Hi:
   When i config the tooltip Point Format as '<span style="color:{point.color}">●</span> {series.name}: <b>{point.y}</b><br/><span style="color:{point.color}">●</span> {series.name}: <b>{point.percentage}%</b><br/>',i get the show like this
![image](https://cloud.githubusercontent.com/assets/4425141/23545641/2c673fbc-0037-11e7-8b55-867917f2053b.png)
How can i format the point.percentage as 20.93.

**Comment by phoenixrip** [comment]
you can specify how many decimals you want to use by adding a little but of code.

Here is the code for point percentage to 2 decimal places:

`{point.percentage:.2f}%`

you can find more info and options on how you can format these numbers [here](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting)
