### ISSUE TITLE
How to activate the advanced mode?

### ISSUE THREAD

**Issue by ElGringo** [highcharts/highcharts-editor#130]
Hi,

I downloaded the precompiled versions with the advanced editor. But the advanded option is not showing in wordpress. Is there anything I have to do to activate it?

Thank you and best regards

Rico

**Comment by cvasseng** [comment]
Hi,

you need to copy the advanced script (`highcharts-editor.advanced.min.js`) in the Wordpress plugin folder, and add the following to `highcharts-editor.php`:
        
        wp_enqueue_script("highcharts-advanced",  plugin_dir_url(__FILE__) . "highcharts-editor.advanced.min.js");
        
Note that there are issues currently with the advanced mode, specifically dealing with lists of things nested in the visual tree. There's an upcoming fix to this, which will land in a couple of weeks.

**Comment by cvasseng** [comment]
As a related side-note: the next version will have a settings page for the WP plugin where advanced mode can be toggled with a checkbox.

**Comment by ElGringo** [comment]
👍 Thank you!
Looking forward for that release.
