### ISSUE TITLE
How can i  add the map for svg

### ISSUE THREAD

**Issue by popoyz** [highcharts/highcharts-editor#131]
Hi:
   I would like to join the map in svg inside, so i can use highmaps anymore.

**Comment by cvasseng** [comment]
Hi, sorry but your question is a bit unclear - are you asking how to use highmaps in the editor?  

If so, Highmaps is not currently supported, but support is being worked on. Release will be sometime in Q2.

**Comment by popoyz** [comment]
Yes,That's my mean.i am looking forward to it.

**Comment by popoyz** [comment]
@cvasseng Hi,I would like to know whether this function is normally developed

**Comment by cvasseng** [comment]
Highmaps support was postponed due to the integration of the editor into our [cloud product](https://cloud.highcharts.com). It's currently tentatively planned around Q2/Q3, but this is subject to change.
