### ISSUE TITLE
External CSS is always registered

### ISSUE THREAD

**Issue by arogachev** [highcharts/highcharts-editor#136]
Hi! First of all, thanks for this plugin and all your work! 

Currently the plugin forcibly registers external CSS (https://github.com/highcharts/highcharts-editor/blob/50722e5b2c8b68c2e7b257dc7f442ad70484f966/src/core/highcharts-editor.js#L705-L709) - Font Awesome and 2 Google Fonts.

```js
//Inject dependencies
highed.ready(function () {
    highed.include('https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css');
    highed.include('https://fonts.googleapis.com/css?family=Roboto:400,300,100,700|Source Sans:400,300,100', false, true);
});
```

Quote from [README](https://github.com/highcharts/highcharts-editor#features):

> Light on dependencies: requires only Highcharts, FontAwesome, and (optionally) two Google Fonts

So saying "optionally" is not quite true here. Both CSS files are always registered and can not be disabled / changed.

This can be a problem if Font Awesome is already used on page with plugin and lead to extra request. Also someone may want to load it from their own server, not CDN; someone is fine with default fonts and don't want to use Google Fonts, etc.

Including of this should be either configurable / optional or managed manually. I think it's completely fine to set this manually along with other CSS / JS dependencies, also it's more explicit and intuitive.

By the way you are using manual registering in `app/index.html` here - https://github.com/highcharts/highcharts-editor/blob/50722e5b2c8b68c2e7b257dc7f442ad70484f966/app/index.html#L8-L9 (I don't know if this file is up-to-date):

```html
<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,700|Source Sans:400,300,100' rel='stylesheet' type='text/css'/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
```

**Comment by cvasseng** [comment]
The default inclusion can now be disabled by setting `highed.option('autoIncludeDependencies', false);` somewhere in `<head>`. 

I hesitate to make it not include it automatically by default as it would break a lot of existing applications.
