### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by ThreepE0** [highcharts/highcharts-editor#139]
I'm sure this is something silly I'm missing, but I can't find anything in the docs so I'm opening an issue;  How do you enter a date format in the "Date Format" field?  I tried things like ''dd-mm-yyyy" and "%A %b %d %T %Z %Y" but I can't get anything to work.

**Comment by davidfrothin** [comment]
same issue for me. I cant find how to adjust date format with a csv import. Entering %d/%m/%Y etc does not detect the format while importing.

@OceansCrashing - Any luck on getting this sorted?
