### ISSUE TITLE
Values over 100 divided by 100 unless the number is followed by a .0

### ISSUE THREAD

**Issue by DuncanUszkay1** [highcharts/highcharts-editor#140]
Is this intended behavior? I can't find any mention of it in the issues or the docs.
<img width="1199" alt="screen shot 2017-06-13 at 3 57 45 pm" src="https://user-images.githubusercontent.com/8670351/27101886-5d84e4b8-5051-11e7-93a6-581a54aafd93.png">

**Comment by cvasseng** [comment]
This is an issue with the CSV parser. It will be improved quite a lot when the new CSV parser in Highcharts is released (likely in 5.0.14).

That said, this particular dataset works as expected in the master branch currently, but this branch is not well-tested for production use.

**Comment by cvasseng** [comment]
Fixed in latest release, please reopen or resubmit if the issue resurfaces.
