### ISSUE TITLE
Can not change chart.type when it is set in default Options

### ISSUE THREAD

**Issue by shelterless** [highcharts/highcharts-editor#141]
If ] does not set chart type in default options , it's work properly.

but when i set chart type in **default options**, i can't change it into another chart type.

can you help me ?

**Comment by cvasseng** [comment]
I'm sorry but I don't quite understand what you mean. Which default options are you talking about?

**Comment by pawelfus** [comment]
Thank you for the details, you are right it's a bug.

**Comment by marubalcava** [comment]
Hello, any updates on this one?

**Comment by roborto444** [comment]
Has this been fixed in recent releases?

**Comment by cvasseng** [comment]
@kai2468 could you take a look at this?

**Comment by cvasseng** [comment]
This has been fixed in master now through f0cc756c3153e01a883259f207e150aae4e1133b.

To use master, clone the repository and follow the instructions here https://github.com/highcharts/highcharts-editor#installing-and-building.

**Comment by lovelyelfpop** [comment]
Bug still exsits in 0.2.2-rc3
