### ISSUE TITLE
When is the next Version arriving?

### ISSUE THREAD

**Issue by ElGringo** [highcharts/highcharts-editor#142]
I know, this is not really an issue. I did not know where to post that. 
Since there are so many problems with the actual beta. Is there by any chance a release date for the next version? Or is a newer one where some of the more important things are fixed somehow availabe?

Thank you

eg

**Comment by cvasseng** [comment]
You could try building your own distribution from master (if you haven't already), which is  some ways ahead of the pre-built releases in terms of both stability, and features. However, if you do, bear in mind that the master branch is technically unstable, so it may have other issues we haven't caught yet.

The next stable release will likely arrive sometime in August.

**Comment by laurencedorman** [comment]
August having slid by, is there any update on this?

**Comment by ravipas87** [comment]
Hi @cvasseng, I din't want to open another issue with this same topic but is there any progress on this? The master branch seems to be very inestable I can`t even show the default templates I have been able to add some templates but aren't working as expected.

**Comment by cvasseng** [comment]
We expect a new release in mid-november at this point.

The master branch has a few changes to the templating system. The templates are now separate from the main build. This means that you have to explicitly include the templates in your project. They end up in `dist/modules/<product family>` (e.g. `dist/modules/highcharts/highcharts-editor-module.highcharts.js`) once you run `gulp`. 

The format for templates has been changed too, to include additional meta information (such as links to appropriate sample data for a given template).

The format is now:
``
{
    "title": "Template Name",
    "description": "Template description",
    "thumbnail": "ThumbnailURL",
    "sampleSets": [<strings pointing to sample sets in `src/products/x/samples>],
    "config": {
        "title": {
            "text": "I am a template!"
        }
    }
});
``

and they're added to the editor by calling `highed.templates.add(category, definition)`, where `category` is a string, and `definition` is an object following the above definition.

**Comment by cvasseng** [comment]
The new release has finally gone live. 

The release pages has been updated, as well as the live demo on http://editor.highcharts.com.

Note that there are quite a few design changes, so you might want to to try it before upgrading it for your project.
