### ISSUE TITLE
Editing Highcharts after Initial Save

### ISSUE THREAD

**Issue by rohanabraham** [highcharts/highcharts-editor#144]
The Highcharts Editor works well. We are able to create a chart, setup the data and get things working. Once completed, the 

var jsonData = JSON.stringify(gChart.toProject());
//This exports the chart and we get a copy of the data.

After this is complete, the user can come back and edit a chart, at this point. The data gets loaded back into the chart and the settings go back into the Editor all correctly.

gChart.loadProject(JSON.parse( saved_JSON_object  ));
//This loads all the chart settings

But the data is missing from the "Data" tab and the "Import" tab. Is there a way to load the data into the project.

**Steps to recreate**
1) Go to High Charts Editor http://editor.highcharts.com/full.html
2) Use sample data and create a chart
3) Click on "Save Project" to get the JSON file
4) Reload the page
5) Click on "Load Project" and use the same JSON file

Expected:
Chart loaded, Customisation active and CSV data visible

Actual:
Chart Loaded - OK, Customisation active - OK, CSV data - Not visible

This is also a problem if the Data tab is activated, we don't get the data. What is the best approach to also load the CSV data text area with the original data?

**Comment by cvasseng** [comment]
If you build your own distribution (clone the repository and run `npm install && gulp complete` to get a bundle in `dist/`) the issue with data persistence should be fixed, and the grid should be populated as expected when loading projects.

**Comment by cvasseng** [comment]
This is fixed in the latest release.
