### ISSUE TITLE
Detection of scripts checks only scripts of CDN

### ISSUE THREAD

**Issue by sbt2486** [highcharts/highcharts-editor#150]
[related_part_of_highed.chartpreview.txt](https://github.com/highcharts/highcharts-editor/files/1535120/related_part_of_highed.chartpreview.txt)
This happens in `getEmbeddableJavaScript()` and prevents me from using the library because I'm adding the highcharts files from my own server. The problematic code is the attached and part of `highed.chartpreview.js`. 

The main problem is the code checks for existing scripts only against the CDN urls so doesn't include locally included scripts and thus the CDN scripts get added again, even though they were added on the local server already.

The whole thing here seems rather hacky. How about at least using feature detection instead of parsing and checking for the existing CDN urls in script tags?

**Comment by cvasseng** [comment]
In the latest version, you can set the global option `includeCDNInExport` to skip including CDN scripts: `highed.option('includeCDNInExport', false)`.
