### ISSUE TITLE
Import chart json in highchart editor to load the same chart options for Modal Editor

### ISSUE THREAD

**Issue by a3aakash** [highcharts/highcharts-editor#151]
Hi All,

Please help me out for importing my json data in the highchart modal editor to show the same chart options which was selected for making the chart. Problem I am unable to hold the highchart options in the editor.

Please solve this out as it is urgent to me.

**Comment by cvasseng** [comment]
Hi,

in the latest release, which just went live, you can do:

`modalEditor.editor.chart.options.setAll(<configuration>)` to load basic JSON configurations. This will overwrite existing chart options with the one you supply.

It's recommended that you use the project format if you plan on continuing editing the chart though, which can be saved/loaded either by using the Save/Open icons in the toolbar, or by calling: `editor.chart.toProject()` and `editor.chart.loadProject(<project data>)`.

**Comment by a3aakash** [comment]
Thank you @cvasseng. I will download the latest release and do the same thing. Please update your documentation file as well so that in future if there will be anything I want to check I will refer that.
