### ISSUE TITLE
Connect with external data source

### ISSUE THREAD

**Issue by ms4hafiz** [highcharts/highcharts-editor#156]
Hi;

Has anybody ever tried to connect or consume data from database like MySQL, or PostGre. I need such functionality with my project.

Thank you

**Comment by cvasseng** [comment]
Hi,

you need to expose your dataset through an API, and then build a custom import plugin to pull it in. In other words, you can't connect directly to a database from the editor, you need a layer in-between that can perform the fetches and return the results over HTTP.

There's an example plugin that pulls in data from an API service [here](https://github.com/highcharts/highcharts-editor/blob/master/plugins/data-socrata.js) and [here](https://github.com/highcharts/highcharts-editor/blob/master/plugins/data-difi.js) you could use as a starting point.
