### ISSUE TITLE
A new importer plugin is not loaded

### ISSUE THREAD

**Issue by damianmarti** [highcharts/highcharts-editor#160]
#### Expected behaviour

From the doc https://github.com/highcharts/highcharts-editor/wiki/Plugins

To enable a importer plugin:

highed.Editor(...,{importer: {plugins: ['NAME']}});

#### Actual behaviour

The plugin is not enabled.

Looking at the highchart editor code, it seems like the options from the Editor is never passed to the DataImporter, and the DataImporter always use the default plugins (['CSV', 'JSON', 'Difi', 'Socrata', 'Google Spreadsheets'])

#### Reproduction steps
Create a new plugin and try to enable it.

#### Editor version
v0.2.0

#### Affected browser(s)

All

**Comment by cvasseng** [comment]
Hi, in case you missed it, this was fixed in 61bebe2. Please re-open this or submit a new issue if you have any further issues with getting your plugin to appear.
