### ISSUE TITLE
TinyMce editor plugin in Episerver

### ISSUE THREAD

**Issue by bryan-moore** [highcharts/highcharts-editor#179]
Hello, I'm try to get editor plugin working in the latest version of Episerver along with TinyMce 4. Everything works normal. The only thing is the editor doesn't write the svg preview of the chart in TinyMce. The chart data is written, but no svg tag. It also doesn't preview in the editor in the right side panel.

#### Expected behaviour
Show the svg preview chart in TinyMce.

#### Actual behaviour
TinyMce has no chart preview.

#### Reproduction steps
Starting with a empty TinyMce area, Insert Highchart, Editor opens as expected, Import sample data, table fills with data, no preview shown in preview area. Click "save and use". I can see the chart data using the code preview in TinyMce. Chart data is saved, but with no svg data. I have no console errors. I want to add the svg plugin doesn't show a preview. Also I am able to export the chart as an svg when it is rendered outside tinymce.

#### Editor version
I have tried both 0.2.1 and 0.2.2. I notice on your demo page you are using 2.1.

#### Affected browser(s)
Using chrome for development.

![tiny1](https://user-images.githubusercontent.com/1242100/44723963-c1bbd780-aad1-11e8-95ab-aadb2bceee61.png)
![tiny2](https://user-images.githubusercontent.com/1242100/44723972-c5e7f500-aad1-11e8-8586-d52cd5b8834a.png)

**Comment by eirikmik** [comment]
@bryan-moore I'm having the same problem, how did you resolve this?

**Comment by eirikmik** [comment]
Answering my own question and perhaps helping someone else struggling with the same: importing the Highcharts data module solved the issue with blank chart.
