### ISSUE TITLE
Standalone not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-editor#194]
#### Behaviour
I have downloaded and opened the Stand alone build in version 0.3.0.

I can see a big red info box with text:
```
There's a problem with your chart!
[object Object]
```

Chart is not created after data is supplied. There is no preview of the chart when trying to edit the chart in customize tab. Template view is empty - list is empty, nothing there.

There is no error in console other than a missing .gif image.

**Comment by ygalescot** [comment]
Hey @KacperMadej,

I have exactly the same problem as you. What solution did you find ?

Thanks,

Youri

**Comment by KacperMadej** [comment]
I have updated the Standalone build and the issue was gone.
The fix was done without version change, so a fresh download, even if the version matches, is suggested.

If this doesn't help please provide more info and we could reopen this issue.

**Comment by dgroh** [comment]
I have the same issue using the latest 0.3.0. Would not make sense to output what is wrong instead of only telling: "There is a problem with your chart?"

**Comment by melanki** [comment]
I tried building Highcharts Editor 0.3.0 using node v8.9.3 and gulp cli 2.3.0 / local 3.9.1
Getting the same error.
