### ISSUE TITLE
resetting a series color shows the default array

### ISSUE THREAD

**Issue by daemth** [highcharts/highcharts-editor#70]
resetting a series color shows the default array of colors instead of one single color:

![schermafdruk 2016-10-31 12 47 18](https://cloud.githubusercontent.com/assets/3327763/19853198/318da830-9f68-11e6-877b-2493a4fa000a.png)

**Comment by cvasseng** [comment]
Fixed in 456b49290c9cd0f348760e29f49ea9a30e173041.

The fix is kind of hacky, but that particular subsystem needs a future refactoring, so a quick fix is fine for now.
