### ISSUE TITLE
No multiple axis option support

### ISSUE THREAD

**Issue by hisen630** [highcharts/highcharts-editor#72]
multiple axis is a quite normal demand, i checked the doc and played quite a bit without finding an option to add a secondary y-axis.

**Comment by cvasseng** [comment]
Multiple axis requires advanced mode. See [docs here](https://github.com/highcharts/highcharts-editor/wiki/Enable-Advanced-Customization) for how to enable it.

Once enabled, a separate tab ("Advanced") will appear in the customizer step. When navigating to the advanced tab, clicking the "+" icon next to the axis of your choice in the left-side tree will let you add a new axis. Note that currently you can only attach series to axis by supplying an index (done on the series in advanced mode). A dropdown will be added in the future.

![Screenshot](https://cloud.githubusercontent.com/assets/1998167/19999598/8a693b28-a273-11e6-92f9-d5fe92bd36f0.png)

**Comment by TorsteinHonsi** [comment]
Currently it is possible, but not trivial. We should make it easy to do in the Simple editor view.

**Comment by hisen630** [comment]
This is great!
