### ISSUE TITLE
import data from database dynamically

### ISSUE THREAD

**Issue by iamsome1** [highcharts/highcharts-editor#73]
Hi,

I want to know how to import data to Highcharts editor from a database dynamically, I tried in beta version it has data source options like csv, google spreadsheet, etc. Is there any way to import from database?

**Comment by cvasseng** [comment]
The Highcharts Editor is completely client side, and so has no built-in way of retrieving data from databases.

However - you can use the plugin-system if your dataset is exposed through a standard HTTP API. 

See the "Import" section [here](https://github.com/highcharts/highcharts-editor/wiki/Plugins).
