### ISSUE TITLE
Modal wont close.

### ISSUE THREAD

**Issue by VictorioBerra** [highcharts/highcharts-editor#79]
I wish I could provide a fiddle but since the assets are zipped and not hosted on a CDN I cant do that yet. I am also inside an AngularJS app if that matters.

Chrome - Version 54.0.2840.99 m (64-bit)
highed - v0.1.1-beta

```
highed.ModalEditor(document.body, {
    features: 'customize done'
});
```

**Comment by cvasseng** [comment]
Hi, are you getting any errors in the chrome console when trying to close it?

**Comment by VictorioBerra** [comment]
No errors in the console. If you grab my index page from my other issue you
might be able to easily replicate this. Download the beta zip and put the
index page in it and run it.

**Comment by cvasseng** [comment]
Hi, the first argument to `highed.ModalEditor` is the node which should summon the editor - not the target for the editor itself. See docs [here](https://github.com/highcharts/highcharts-editor/wiki/Editors#highedmodaleditorsummoner-attributes-fn---constructor).

Try:

    highed.ModalEditor('my-button', {
        ...
    });

Instead, where 'my-button' is the id of the button that should spawn the modal editor. There's no need to add additional event listeners on the button, the modal editor does that for you.
