### ISSUE TITLE
How do I get rid of the importer section on the simple modal editor?

### ISSUE THREAD

**Issue by VictorioBerra** [highcharts/highcharts-editor#80]
![importer](http://i.imgur.com/0EpteFS.png)

See yellow area.

```Javascript
highed.ModalEditor(document.body, {
    type: 'simple',
    features: 'customize done',
    allowDone: true,
    importer: {
        options: ''
    }
});
```

I added importer.options = '' just now. It removes everything but CSV.

**Comment by cvasseng** [comment]
The simple editor now supports the `features` attribute. To disable the importer:
    
    highed.ModalEditor(document.body, {
        type: 'simple',
        features: '',
        allowDone: true,
        importer: {
            options: ''
        }
    });
