### ISSUE TITLE
The First Data cann't be empty

### ISSUE THREAD

**Issue by popoycol** [highcharts/highcharts-editor#86]
Hi,
   When i type like this ,i got the image.
![image](https://cloud.githubusercontent.com/assets/4425141/20887244/d2fb7c14-bb34-11e6-9fdc-77d99d837ad9.png)
  But when i type like the following , i got nothing.
![image](https://cloud.githubusercontent.com/assets/4425141/20887301/fdbd506c-bb34-11e6-803b-c70fd10eb3d3.png)

**Comment by cvasseng** [comment]
Hi,

thanks for reporting. There's an upcoming feature addition that takes care of this as well as other issues with data importing. It's currently scheduled for a December preview release.

**Comment by popoycol** [comment]
That's great. Thank you.
