### ISSUE TITLE
Export date from json 

### ISSUE THREAD

**Issue by popoycol** [highcharts/highcharts-editor#87]
Hi:
   When i create data like the following , i got the right image.
![image](https://cloud.githubusercontent.com/assets/4425141/20887376/43b3d5fa-bb35-11e6-9ea9-145884bb9646.png)
   But when i export json , i got the following json that only contain timestramp.
![image](https://cloud.githubusercontent.com/assets/4425141/20887431/7f6392e8-bb35-11e6-925f-0a156a821951.png)
   When i select the x-axis as datetime , it's right. But other will be this.
![image](https://cloud.githubusercontent.com/assets/4425141/20887564/18d6208a-bb36-11e6-89dd-2a8e62be02b1.png)
   I think the time format should be consistent with the input and output.

**Comment by cvasseng** [comment]
Hi,

thanks for reporting.

There's an upcoming feature addition that makes the importing more streamlined, stable, and predictable. One of the main focuses is to correctly handle dates. The issue you're describing is one of the issues that it aims to fix. :)

ETA is before year-end.
