### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by ld0rman** [highcharts/highcharts-editor#88]
Would you be interested in this feature? I am going to have to translate the interface into French and  I was wondering if you would accept a Pull Request.

**Comment by ld0rman** [comment]
Ah, I see you've started this in highed.localization.js, but it doesn't yet cover the entirety of the strings used in the interface

**Comment by cvasseng** [comment]
Hi, 

getting the bulk of the missing strings into the localization system requires refactoring the underlying meta structure used for properties. It's on my list, but I don't have a clear ETA at the moment. 

A temporary workaround could be to do translations for the attributes/etc. directly in dictionaries/meta.js (run `node tools/update.meta.js` to see your changes). I could then help you merge that into the upcoming system once it's in place. 

My goal with localization is to be able to offer language packs (as well as an easy way of doing translations), so we'd of course love a pull request for this when it's ready!

**Comment by berdeter** [comment]
Having the editor would be nice to have but more important for my would be to have localization tab for several languages.

I can consider teaching the people editing graphs how to do it with the English interface (not easiest thing to do but it is doable). In the other end users of the web site can switch active language it is very important that the graph can display in the corresponding language.

Let's say your web site is available in french and english, the texts shown by Highcharts in live should follow.

**Comment by cvasseng** [comment]
@berdeter: That can be done in the Localization pane in the customizer.

---

The localization system has now been extended to encompass the options provided by the simple customizer. Translation setup for advanced mode will follow at a later date. Documentation can be found [here](https://github.com/highcharts/highcharts-editor/wiki/Localization).
