### ISSUE TITLE
Highcharts editor should allow advanced breaks configuration

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts-editor#90]
It would be nice to be able to configure breaks similar to the ones proposed in the api documentation here : http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/axisbreak/break-visualized/

Simple breaks are a bit buggy and the lack of feedback on the presence of a break can introduce misunderstandings

**Comment by cvasseng** [comment]
This can now be done using the custom code pane.
