### ISSUE TITLE
Highcharts editor plot lines configuration crash the editor

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts-editor#91]
Message : type error (Intermediate value).concat is not a function.

Several problems encountered : 

- plot lines is documented as an array and the editor shows a single entry similar to #89 
- whenever you try to enter a value in this dialog you get a toast with the error
- as soon as you have had the error your whole configuration is doomed and all is broken untill you reload the page. Removing the value is not enough
![capture](https://cloud.githubusercontent.com/assets/853740/20969741/a7de49ba-bc8a-11e6-966f-15114fdb669d.PNG)

**Comment by cvasseng** [comment]
See #95
