### ISSUE TITLE
highcharts editor modal bug

### ISSUE THREAD

**Issue by crh225** [highcharts/highcharts-editor#93]
Expected behaviour

the dates are not showing up correctly when using the sample data for the modal on http://editor.highcharts.com/modal.html

![](https://cloud.githubusercontent.com/assets/19475195/20934986/aaea306c-bba2-11e6-8650-56b240ef8e08.png)

Actual behaviour

![](https://cloud.githubusercontent.com/assets/19475195/20934953/93c202a2-bba2-11e6-9533-8c527366615a.png)

Live demo with steps to reproduce

http://editor.highcharts.com/modal.html

Affected browser(s)

all

**Comment by crh225** [comment]
if you see the x axis, you can see they dont show up correctly either:

![](https://cloud.githubusercontent.com/assets/19475195/20935016/c59e6a54-bba2-11e6-887d-c4d7bc4d46ba.png)

same applies to http://editor.highcharts.com/full.html

**Comment by crh225** [comment]
see https://github.com/highcharts/highcharts/issues/6099

**Comment by cvasseng** [comment]
Hi,

thanks for reporting.

There's an upcoming feature addition that makes the importing more streamlined, stable, and predictable. One of the main focuses is to correctly handle dates, so it will fix cases such as this.

ETA is before year-end.

**Comment by cvasseng** [comment]
See #96
