### ISSUE TITLE
Issues with properties in nested arrays in advanced mode

### ISSUE THREAD

**Issue by cvasseng** [highcharts/highcharts-editor#95]
A refactor of the data interface is required to support nested arrays.

The bug impacts all array options within nested arrays, such as:
  * Breaks
  * Labels

**Comment by berdeter** [comment]
Thank you for considering this bug. Please note that it is quite likely that the problem occurs in more item types. You should run through the API documentation beside the editor and every time you have a [array of something] in the documentation there should be a collection in the editor ...

**Comment by cvasseng** [comment]
Hi,

yes, as you say the bug impacts more things. Every option that's indirectly or directly in nested arrays are affected in advanced mode. This means that all array options contained in e.g. series and axis will not work as expected. 

The fix will be part of an upcoming structural change which address some additional architectural issues as well as this one.

**Comment by berdeter** [comment]
Just noticed you have the same problem with zones

**Comment by cvasseng** [comment]
Yes, it impacts every property contained within an array that is also contained within an array - regardless of how deeply nested the inner array is.
