### ISSUE TITLE
Revamp the data import

### ISSUE THREAD

**Issue by cvasseng** [highcharts/highcharts-editor#96]
Expand import functionality to:
  * Utilize a data grid
  * Better date parsing
  * More tolerant to malformed input

This revamp deals with integrating the data grid, and improving the CSV parser.

**Comment by berdeter** [comment]
+ Add the possibility to load data from an REST URL providing JSON or CSV content
+ Add the possibility to load data related information such as thickPositions, plotilines etc

**Comment by cvasseng** [comment]
@berdeter The data import revamp is centered around incorporating a data grid and improving the CSV parser. Loading data through REST can be done by writing a custom [import plugin](https://github.com/highcharts/highcharts-editor/wiki/Plugins). Chart properties should be loaded through one of the JSON interfaces.
