### ISSUE TITLE
Delete button on series does not work

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts-editor#97]
Advanced mode
Click the - to delete a serie
Get a prompt. Say OK
The entry stays there
![capture](https://cloud.githubusercontent.com/assets/853740/21015478/6a5ba9ce-bd62-11e6-99a3-5c91b093178c.PNG)

PS : it is likely that it can be reproduced on other entry types ...

**Comment by cvasseng** [comment]
Thanks for reporting.

I will look into it.
